import { Disclosure, Transition } from '@headlessui/react'

const Answer = ({ answer }) => {
    return (
        <div className="md:row-span-2 col-span-4 md:col-span-2 max-h-full bg-githubTheme-blue300 bg-opacity-5  rounded-md p-2 mb-5">
            <div className="w-full px-4 pt-4">
        <Disclosure>
          {({ open }) => (
            <>
              <Disclosure.Button className="flex justify-start items-center w-full text-sm font-medium text-left ">
                <svg className={`transition-all duration-300 ease-in-out ${
                    open ? 'transform rotate-90 ' : ''
                } w-5 h-5 mr-2 text-githubTheme-blue200`} fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d={`${open ? 'M9 5l7 7-7 7' : 'M13 5l7 7-7 7M5 5l7 7-7 7' }`}></path></svg>
                <span className="text-lg flex flex-row items-center justify-between space-x-2 w-full"><span>Answer</span> <span className="bg-githubTheme-yellow bg-opacity-90 text-gray-900 font-semibold text-xs px-2 py-1 rounded-full">Click to { open ? "close" : "view"}</span></span>
              </Disclosure.Button>
              <Transition show={open} 
                enter="transition-opacity duration-300 ease-in-out"
                enterFrom="opacity-0"
                enterTo="opacity-100"
                leave="transition-opacity duration-300 ease-in-out"
                leaveFrom="opacity-100"
                leaveTo="opacity-0"
                >
                <Disclosure.Panel className="px-4 pt-4 pb-2 text-sm text-gray-100 transition-all duration-300">
                <span className="text-xl block my-2">Answer: <span className="font-bold text-xl text-githubTheme-blue200">A</span></span>
                    <span className="text-base">
                        String is a built-in constructor, which we can add properties to. I just added a method to its prototype. Primitive strings are automatically converted into a string object, generated by the string prototype function. So, all strings (string objects) have access to that method!
                    </span>
                </Disclosure.Panel>
              </Transition>
            </>
          )}
        </Disclosure>
    </div>
        </div>
    )
}

export default Answer ;